"""initial crm schema

Revision ID: 2dcd96d33fe8
Revises: 
Create Date: 2026-05-07 06:47:17.997366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2dcd96d33fe8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('crm', 'financial_report', 'transaction', 'external_registry', 'api', 'file', name='data_source_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_data_sources_code'), 'external_data_sources', ['code'], unique=True)
    op.create_index(op.f('ix_external_data_sources_source_type'), 'external_data_sources', ['source_type'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('algorithm_name', sa.String(length=120), nullable=True),
    sa.Column('target_name', sa.String(length=120), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_ml_model_name_version')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('segment', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('annual_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_bin'), 'organizations', ['bin'], unique=True)
    op.create_index(op.f('ix_organizations_industry'), 'organizations', ['industry'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_region'), 'organizations', ['region'], unique=False)
    op.create_index(op.f('ix_organizations_segment'), 'organizations', ['segment'], unique=False)
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('organization_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_contacts_organization_id'), 'organization_contacts', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('data_import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='import_status'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_success', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['external_data_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_import_batches_source_id'), 'data_import_batches', ['source_id'], unique=False)
    op.create_index(op.f('ix_data_import_batches_status'), 'data_import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_data_import_batches_uploaded_by_id'), 'data_import_batches', ['uploaded_by_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('new', 'negotiation', 'approved', 'rejected', 'closed', name='deal_stage'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_organization_id'), 'deals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_deals_stage'), 'deals', ['stage'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('organization_card', 'risk_summary', 'portfolio_analytics', 'model_quality', name='report_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'failed', name='report_status'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_by_id'), 'reports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('interaction_type', sa.Enum('call', 'email', 'meeting', 'note', 'task', name='interaction_type'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_deal_id'), 'interactions', ['deal_id'], unique=False)
    op.create_index(op.f('ix_interactions_happened_at'), 'interactions', ['happened_at'], unique=False)
    op.create_index(op.f('ix_interactions_interaction_type'), 'interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_interactions_organization_id'), 'interactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('risk_feature_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debt_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overdue_days_30', sa.Integer(), nullable=False),
    sa.Column('overdue_days_90', sa.Integer(), nullable=False),
    sa.Column('disputes_count', sa.Integer(), nullable=False),
    sa.Column('transactions_count', sa.Integer(), nullable=False),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('raw_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['data_import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period_date', name='uq_risk_feature_snapshot_period')
    )
    op.create_index(op.f('ix_risk_feature_snapshots_import_batch_id'), 'risk_feature_snapshots', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_risk_feature_snapshots_organization_id'), 'risk_feature_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_feature_snapshots_period_date'), 'risk_feature_snapshots', ['period_date'], unique=False)
    op.create_table('risk_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('feature_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risk_level'), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='ck_risk_predictions_score_range'),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['risk_feature_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_predictions_feature_snapshot_id'), 'risk_predictions', ['feature_snapshot_id'], unique=False)
    op.create_index(op.f('ix_risk_predictions_model_id'), 'risk_predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_risk_predictions_organization_id'), 'risk_predictions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_predictions_predicted_at'), 'risk_predictions', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_risk_predictions_risk_level'), 'risk_predictions', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_predictions_risk_level'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_predicted_at'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_organization_id'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_model_id'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_feature_snapshot_id'), table_name='risk_predictions')
    op.drop_table('risk_predictions')
    op.drop_index(op.f('ix_risk_feature_snapshots_period_date'), table_name='risk_feature_snapshots')
    op.drop_index(op.f('ix_risk_feature_snapshots_organization_id'), table_name='risk_feature_snapshots')
    op.drop_index(op.f('ix_risk_feature_snapshots_import_batch_id'), table_name='risk_feature_snapshots')
    op.drop_table('risk_feature_snapshots')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_organization_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_interaction_type'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_happened_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_deal_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_by_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_deals_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_organization_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_data_import_batches_uploaded_by_id'), table_name='data_import_batches')
    op.drop_index(op.f('ix_data_import_batches_status'), table_name='data_import_batches')
    op.drop_index(op.f('ix_data_import_batches_source_id'), table_name='data_import_batches')
    op.drop_table('data_import_batches')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organization_contacts_organization_id'), table_name='organization_contacts')
    op.drop_table('organization_contacts')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_segment'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_region'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_industry'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_bin'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_external_data_sources_source_type'), table_name='external_data_sources')
    op.drop_index(op.f('ix_external_data_sources_code'), table_name='external_data_sources')
    op.drop_table('external_data_sources')
    # ### end Alembic commands ###
